# Form implementation generated from reading ui file 'theme/customer_options.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_customer_options_form(object):
    def setupUi(self, customer_options_form):
        customer_options_form.setObjectName("customer_options_form")
        customer_options_form.resize(915, 150)
        customer_options_form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(customer_options_form)
        self.gridLayout.setObjectName("gridLayout")
        self.add_customer_vehicle_button = QtWidgets.QPushButton(parent=customer_options_form)
        self.add_customer_vehicle_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.add_customer_vehicle_button.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/Icons/car.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_customer_vehicle_button.setIcon(icon)
        self.add_customer_vehicle_button.setIconSize(QtCore.QSize(30, 30))
        self.add_customer_vehicle_button.setFlat(True)
        self.add_customer_vehicle_button.setObjectName("add_customer_vehicle_button")
        self.gridLayout.addWidget(self.add_customer_vehicle_button, 0, 2, 1, 1)
        self.delete_customer_button = QtWidgets.QPushButton(parent=customer_options_form)
        self.delete_customer_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.delete_customer_button.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/Icons/trash.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_customer_button.setIcon(icon1)
        self.delete_customer_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_customer_button.setFlat(True)
        self.delete_customer_button.setObjectName("delete_customer_button")
        self.gridLayout.addWidget(self.delete_customer_button, 0, 3, 1, 1)
        self.create_ro_customer_button = QtWidgets.QPushButton(parent=customer_options_form)
        self.create_ro_customer_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.create_ro_customer_button.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/Icons/add-document.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.create_ro_customer_button.setIcon(icon2)
        self.create_ro_customer_button.setIconSize(QtCore.QSize(30, 30))
        self.create_ro_customer_button.setFlat(True)
        self.create_ro_customer_button.setObjectName("create_ro_customer_button")
        self.gridLayout.addWidget(self.create_ro_customer_button, 0, 0, 1, 1)
        self.edit_customer_button = QtWidgets.QPushButton(parent=customer_options_form)
        self.edit_customer_button.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/Icons/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.edit_customer_button.setIcon(icon3)
        self.edit_customer_button.setIconSize(QtCore.QSize(30, 30))
        self.edit_customer_button.setFlat(True)
        self.edit_customer_button.setObjectName("edit_customer_button")
        self.gridLayout.addWidget(self.edit_customer_button, 0, 1, 1, 1)
        self.cancel_customer_options_button = QtWidgets.QPushButton(parent=customer_options_form)
        self.cancel_customer_options_button.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/icons3/24x24/cil-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel_customer_options_button.setIcon(icon4)
        self.cancel_customer_options_button.setIconSize(QtCore.QSize(30, 30))
        self.cancel_customer_options_button.setFlat(True)
        self.cancel_customer_options_button.setObjectName("cancel_customer_options_button")
        self.gridLayout.addWidget(self.cancel_customer_options_button, 0, 4, 1, 1)

        self.retranslateUi(customer_options_form)
        QtCore.QMetaObject.connectSlotsByName(customer_options_form)

    def retranslateUi(self, customer_options_form):
        _translate = QtCore.QCoreApplication.translate
        customer_options_form.setWindowTitle(_translate("customer_options_form", "Form"))
        self.add_customer_vehicle_button.setText(_translate("customer_options_form", "Add Vehicle"))
        self.delete_customer_button.setText(_translate("customer_options_form", "Delete"))
        self.create_ro_customer_button.setText(_translate("customer_options_form", "Create RO"))
        self.edit_customer_button.setText(_translate("customer_options_form", "Edit Customer"))
        self.cancel_customer_options_button.setText(_translate("customer_options_form", "Cancel"))
from openauto.theme import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    customer_options_form = QtWidgets.QWidget()
    ui = Ui_customer_options_form()
    ui.setupUi(customer_options_form)
    customer_options_form.show()
    sys.exit(app.exec())
