from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_edit_appt_form(object):
    def setupUi(self, edit_appt_form):
        edit_appt_form.setObjectName("edit_appt_form")
        edit_appt_form.resize(941, 405)
        edit_appt_form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(edit_appt_form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_edit_label = QtWidgets.QLabel(parent=edit_appt_form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.name_edit_label.setFont(font)
        self.name_edit_label.setStyleSheet("")
        self.name_edit_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_edit_label.setObjectName("name_edit_label")
        self.horizontalLayout.addWidget(self.name_edit_label)
        self.name_edit_line = QtWidgets.QLineEdit(parent=edit_appt_form)
        self.name_edit_line.setMinimumSize(QtCore.QSize(0, 30))
        self.name_edit_line.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.name_edit_line.setFont(font)
        self.name_edit_line.setStyleSheet("")
        self.name_edit_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_edit_line.setReadOnly(True)
        self.name_edit_line.setObjectName("name_edit_line")
        self.horizontalLayout.addWidget(self.name_edit_line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vehicle_label = QtWidgets.QLabel(parent=edit_appt_form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.vehicle_label.setFont(font)
        self.vehicle_label.setStyleSheet("")
        self.vehicle_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vehicle_label.setObjectName("vehicle_label")
        self.horizontalLayout_2.addWidget(self.vehicle_label)
        self.vehicle_box = QtWidgets.QComboBox(parent=edit_appt_form)
        self.vehicle_box.setMinimumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.vehicle_box.setFont(font)
        self.vehicle_box.setStyleSheet("")
        self.vehicle_box.setObjectName("vehicle_box")
        self.horizontalLayout_2.addWidget(self.vehicle_box)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time_label = QtWidgets.QLabel(parent=edit_appt_form)
        self.time_label.setMaximumSize(QtCore.QSize(103, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("")
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_3.addWidget(self.time_label)
        self.time_box = QtWidgets.QComboBox(parent=edit_appt_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_box.sizePolicy().hasHeightForWidth())
        self.time_box.setSizePolicy(sizePolicy)
        self.time_box.setMinimumSize(QtCore.QSize(500, 30))
        self.time_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.time_box.setFont(font)
        self.time_box.setStyleSheet("")
        self.time_box.setObjectName("time_box")
        self.horizontalLayout_3.addWidget(self.time_box)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.date_widget = QtWidgets.QCalendarWidget(parent=edit_appt_form)
        self.date_widget.setStyleSheet("")
        self.date_widget.setObjectName("date_widget")
        self.gridLayout.addWidget(self.date_widget, 0, 2, 2, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.notes_label = QtWidgets.QLabel(parent=edit_appt_form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.notes_label.setFont(font)
        self.notes_label.setStyleSheet("")
        self.notes_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notes_label.setObjectName("notes_label")
        self.verticalLayout_2.addWidget(self.notes_label)
        self.notes_appt_edit = QtWidgets.QTextEdit(parent=edit_appt_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.notes_appt_edit.setFont(font)
        self.notes_appt_edit.setStyleSheet("")
        self.notes_appt_edit.setObjectName("notes_appt_edit")
        self.verticalLayout_2.addWidget(self.notes_appt_edit)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 2)
        self.wait_edit_button = QtWidgets.QRadioButton(parent=edit_appt_form)
        self.wait_edit_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.wait_edit_button.setFont(font)
        self.wait_edit_button.setStyleSheet("")
        self.wait_edit_button.setObjectName("wait_edit_button")
        self.gridLayout.addWidget(self.wait_edit_button, 2, 0, 1, 1)
        self.drop_edit_button = QtWidgets.QRadioButton(parent=edit_appt_form)
        self.drop_edit_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.drop_edit_button.setFont(font)
        self.drop_edit_button.setStyleSheet("")
        self.drop_edit_button.setObjectName("drop_edit_button")
        self.gridLayout.addWidget(self.drop_edit_button, 2, 1, 1, 1)
        self.cancel_edit_appt_button = QtWidgets.QPushButton(parent=edit_appt_form)
        self.cancel_edit_appt_button.setMinimumSize(QtCore.QSize(150, 30))
        self.cancel_edit_appt_button.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icons3/24x24/cil-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel_edit_appt_button.setIcon(icon)
        self.cancel_edit_appt_button.setIconSize(QtCore.QSize(30, 30))
        self.cancel_edit_appt_button.setObjectName("cancel_edit_appt_button")
        self.gridLayout.addWidget(self.cancel_edit_appt_button, 2, 2, 1, 1)
        self.confirm_edit_appt_button = QtWidgets.QPushButton(parent=edit_appt_form)
        self.confirm_edit_appt_button.setMinimumSize(QtCore.QSize(150, 30))
        self.confirm_edit_appt_button.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons3/24x24/cil-check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.confirm_edit_appt_button.setIcon(icon1)
        self.confirm_edit_appt_button.setIconSize(QtCore.QSize(30, 30))
        self.confirm_edit_appt_button.setObjectName("confirm_edit_appt_button")
        self.gridLayout.addWidget(self.confirm_edit_appt_button, 2, 3, 1, 1)

        self.retranslateUi(edit_appt_form)
        QtCore.QMetaObject.connectSlotsByName(edit_appt_form)

    def retranslateUi(self, edit_appt_form):
        _translate = QtCore.QCoreApplication.translate
        edit_appt_form.setWindowTitle(_translate("edit_appt_form", "Form"))
        self.name_edit_label.setText(_translate("edit_appt_form", "Customer"))
        self.vehicle_label.setText(_translate("edit_appt_form", "Vehicle"))
        self.time_label.setText(_translate("edit_appt_form", "Time"))
        self.notes_label.setText(_translate("edit_appt_form", "Notes"))
        self.wait_edit_button.setText(_translate("edit_appt_form", "Wait"))
        self.drop_edit_button.setText(_translate("edit_appt_form", "Drop"))
        self.cancel_edit_appt_button.setText(_translate("edit_appt_form", "Cancel"))
        self.confirm_edit_appt_button.setText(_translate("edit_appt_form", "Confirm"))
from openauto.theme import resources_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_appt_form = QtWidgets.QWidget()
    ui = Ui_edit_appt_form()
    ui.setupUi(edit_appt_form)
    edit_appt_form.show()
    sys.exit(app.exec())
