from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vehicle_search_form(object):
    def setupUi(self, vehicle_search_form):
        vehicle_search_form.setObjectName("vehicle_search_form")
        vehicle_search_form.resize(593, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("openauto/theme/../../OpenAutoLite/ui_files/Images/Icons/car.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        vehicle_search_form.setWindowIcon(icon)
        vehicle_search_form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(vehicle_search_form)
        self.gridLayout.setObjectName("gridLayout")
        self.vin_label = QtWidgets.QLabel(parent=vehicle_search_form)
        self.vin_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vin_label.setFont(font)
        self.vin_label.setStyleSheet("")
        self.vin_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_label.setObjectName("vin_label")
        self.gridLayout.addWidget(self.vin_label, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.year_line = QtWidgets.QLineEdit(parent=vehicle_search_form)
        self.year_line.setMinimumSize(QtCore.QSize(50, 30))
        self.year_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.year_line.setFont(font)
        self.year_line.setStyleSheet("")
        self.year_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.year_line.setObjectName("year_line")
        self.horizontalLayout_4.addWidget(self.year_line)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.make_line = QtWidgets.QLineEdit(parent=vehicle_search_form)
        self.make_line.setMinimumSize(QtCore.QSize(0, 30))
        self.make_line.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.make_line.setFont(font)
        self.make_line.setStyleSheet("")
        self.make_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.make_line.setObjectName("make_line")
        self.horizontalLayout_5.addWidget(self.make_line)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.model_line = QtWidgets.QLineEdit(parent=vehicle_search_form)
        self.model_line.setMinimumSize(QtCore.QSize(0, 30))
        self.model_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.model_line.setFont(font)
        self.model_line.setStyleSheet("")
        self.model_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.model_line.setObjectName("model_line")
        self.horizontalLayout_6.addWidget(self.model_line)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.engine_line = QtWidgets.QLineEdit(parent=vehicle_search_form)
        self.engine_line.setMinimumSize(QtCore.QSize(0, 30))
        self.engine_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.engine_line.setFont(font)
        self.engine_line.setStyleSheet("")
        self.engine_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engine_line.setObjectName("engine_line")
        self.horizontalLayout_3.addWidget(self.engine_line)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.trim_line = QtWidgets.QLineEdit(parent=vehicle_search_form)
        self.trim_line.setMinimumSize(QtCore.QSize(0, 30))
        self.trim_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.trim_line.setFont(font)
        self.trim_line.setStyleSheet("")
        self.trim_line.setText("")
        self.trim_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.trim_line.setObjectName("trim_line")
        self.horizontalLayout_7.addWidget(self.trim_line)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 2)
        self.vehicle_save_button = QtWidgets.QPushButton(parent=vehicle_search_form)
        self.vehicle_save_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.vehicle_save_button.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons3/24x24/cil-check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vehicle_save_button.setIcon(icon1)
        self.vehicle_save_button.setIconSize(QtCore.QSize(30, 30))
        self.vehicle_save_button.setFlat(True)
        self.vehicle_save_button.setObjectName("vehicle_save_button")
        self.gridLayout.addWidget(self.vehicle_save_button, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vin_search_button = QtWidgets.QPushButton(parent=vehicle_search_form)
        self.vin_search_button.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/Icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vin_search_button.setIcon(icon2)
        self.vin_search_button.setIconSize(QtCore.QSize(30, 30))
        self.vin_search_button.setFlat(True)
        self.vin_search_button.setObjectName("vin_search_button")
        self.horizontalLayout_2.addWidget(self.vin_search_button)
        self.plate_state_box = QtWidgets.QComboBox(parent=vehicle_search_form)
        self.plate_state_box.setMinimumSize(QtCore.QSize(0, 30))
        self.plate_state_box.setObjectName("plate_state_box")
        self.horizontalLayout_2.addWidget(self.plate_state_box)
        self.vin_line = QtWidgets.QLineEdit(parent=vehicle_search_form)
        self.vin_line.setMinimumSize(QtCore.QSize(0, 35))
        self.vin_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.vin_line.setFont(font)
        self.vin_line.setStyleSheet("")
        self.vin_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_line.setObjectName("vin_line")
        self.horizontalLayout_2.addWidget(self.vin_line)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.vehicle_cancel_button = QtWidgets.QPushButton(parent=vehicle_search_form)
        self.vehicle_cancel_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.vehicle_cancel_button.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/icons3/24x24/cil-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vehicle_cancel_button.setIcon(icon3)
        self.vehicle_cancel_button.setIconSize(QtCore.QSize(30, 30))
        self.vehicle_cancel_button.setAutoRepeatDelay(100)
        self.vehicle_cancel_button.setFlat(True)
        self.vehicle_cancel_button.setObjectName("vehicle_cancel_button")
        self.gridLayout.addWidget(self.vehicle_cancel_button, 4, 0, 1, 1)

        self.retranslateUi(vehicle_search_form)
        QtCore.QMetaObject.connectSlotsByName(vehicle_search_form)

    def retranslateUi(self, vehicle_search_form):
        _translate = QtCore.QCoreApplication.translate
        vehicle_search_form.setWindowTitle(_translate("vehicle_search_form", "Vehicle Search"))
        self.vin_label.setText(_translate("vehicle_search_form", "Search By VIN"))
        self.year_line.setPlaceholderText(_translate("vehicle_search_form", "Year ..."))
        self.make_line.setPlaceholderText(_translate("vehicle_search_form", "Make ..."))
        self.model_line.setPlaceholderText(_translate("vehicle_search_form", "Model ..."))
        self.engine_line.setPlaceholderText(_translate("vehicle_search_form", "Engine ..."))
        self.trim_line.setPlaceholderText(_translate("vehicle_search_form", "Trim ..."))
        self.vehicle_save_button.setText(_translate("vehicle_search_form", "Next"))
        self.vin_search_button.setText(_translate("vehicle_search_form", "VIN Search"))
        self.vin_line.setPlaceholderText(_translate("vehicle_search_form", "VIN ..."))
        self.vehicle_cancel_button.setText(_translate("vehicle_search_form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vehicle_search_form = QtWidgets.QWidget()
    ui = Ui_vehicle_search_form()
    ui.setupUi(vehicle_search_form)
    vehicle_search_form.show()
    sys.exit(app.exec())
