# Form implementation generated from reading ui file '/home/fred/PycharmProjects/OpenAuto/openauto/theme/vehicle_search.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(593, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/fred/PycharmProjects/OpenAuto/openauto/theme/../../OpenAutoLite/ui_files/Images/Icons/car.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("color: black;\n"
"background-color: #ebebe6;\n"
"background-image: none;\n"
"border-radius: 10px;")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.vin_label = QtWidgets.QLabel(parent=Form)
        self.vin_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vin_label.setFont(font)
        self.vin_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_label.setObjectName("vin_label")
        self.gridLayout.addWidget(self.vin_label, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.year_line = QtWidgets.QLineEdit(parent=Form)
        self.year_line.setMinimumSize(QtCore.QSize(50, 30))
        self.year_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.year_line.setFont(font)
        self.year_line.setStyleSheet("border-radius: 5px;\n"
"background-color: #fefeff;\n"
"color: black;")
        self.year_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.year_line.setObjectName("year_line")
        self.horizontalLayout_4.addWidget(self.year_line)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.make_line = QtWidgets.QLineEdit(parent=Form)
        self.make_line.setMinimumSize(QtCore.QSize(0, 30))
        self.make_line.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.make_line.setFont(font)
        self.make_line.setStyleSheet("border-radius: 5px;\n"
"background-color: #fefeff;\n"
"color: black;")
        self.make_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.make_line.setObjectName("make_line")
        self.horizontalLayout_5.addWidget(self.make_line)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.model_line = QtWidgets.QLineEdit(parent=Form)
        self.model_line.setMinimumSize(QtCore.QSize(0, 30))
        self.model_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.model_line.setFont(font)
        self.model_line.setStyleSheet("border-radius: 5px;\n"
"background-color: #fefeff;\n"
"color: black;")
        self.model_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.model_line.setObjectName("model_line")
        self.horizontalLayout_6.addWidget(self.model_line)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.engine_line = QtWidgets.QLineEdit(parent=Form)
        self.engine_line.setMinimumSize(QtCore.QSize(0, 30))
        self.engine_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.engine_line.setFont(font)
        self.engine_line.setStyleSheet("border-radius: 5px;\n"
"background-color: #fefeff;\n"
"color: black;")
        self.engine_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engine_line.setObjectName("engine_line")
        self.horizontalLayout_3.addWidget(self.engine_line)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.trim_line = QtWidgets.QLineEdit(parent=Form)
        self.trim_line.setMinimumSize(QtCore.QSize(0, 30))
        self.trim_line.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.trim_line.setFont(font)
        self.trim_line.setStyleSheet("border-radius: 5px;\n"
"background-color: #fefeff;\n"
"color: black;")
        self.trim_line.setText("")
        self.trim_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.trim_line.setObjectName("trim_line")
        self.horizontalLayout_7.addWidget(self.trim_line)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 2)
        self.save_create_button = QtWidgets.QPushButton(parent=Form)
        self.save_create_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.save_create_button.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"    background-color: #76ABAE;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #828786;\n"
"    color: #fff;\n"
"    border-radius: 10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/fred/PycharmProjects/OpenAuto/openauto/theme/icons3/24x24/cil-check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_create_button.setIcon(icon1)
        self.save_create_button.setIconSize(QtCore.QSize(30, 30))
        self.save_create_button.setFlat(True)
        self.save_create_button.setObjectName("save_create_button")
        self.gridLayout.addWidget(self.save_create_button, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vin_search_button = QtWidgets.QPushButton(parent=Form)
        self.vin_search_button.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"    background-color: #76ABAE;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #828786;\n"
"    color: #fff;\n"
"    border-radius: 10px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/fred/PycharmProjects/OpenAuto/openauto/theme/Icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vin_search_button.setIcon(icon2)
        self.vin_search_button.setIconSize(QtCore.QSize(30, 30))
        self.vin_search_button.setFlat(True)
        self.vin_search_button.setObjectName("vin_search_button")
        self.horizontalLayout_2.addWidget(self.vin_search_button)
        self.vin_line = QtWidgets.QLineEdit(parent=Form)
        self.vin_line.setMinimumSize(QtCore.QSize(0, 35))
        self.vin_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.vin_line.setFont(font)
        self.vin_line.setStyleSheet("border-radius: 5px;\n"
"background-color: #fefeff;\n"
"color: black;")
        self.vin_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_line.setObjectName("vin_line")
        self.horizontalLayout_2.addWidget(self.vin_line)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.abort_button = QtWidgets.QPushButton(parent=Form)
        self.abort_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.abort_button.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"    background-color: #A0153E;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C49497;\n"
"    color: #fff;\n"
"    border-radius: 10px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/fred/PycharmProjects/OpenAuto/openauto/theme/icons3/24x24/cil-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.abort_button.setIcon(icon3)
        self.abort_button.setIconSize(QtCore.QSize(30, 30))
        self.abort_button.setAutoRepeatDelay(100)
        self.abort_button.setFlat(True)
        self.abort_button.setObjectName("abort_button")
        self.gridLayout.addWidget(self.abort_button, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Vehicle Search"))
        self.vin_label.setText(_translate("Form", "Search By VIN"))
        self.year_line.setPlaceholderText(_translate("Form", "Year ..."))
        self.make_line.setPlaceholderText(_translate("Form", "Make ..."))
        self.model_line.setPlaceholderText(_translate("Form", "Model ..."))
        self.engine_line.setPlaceholderText(_translate("Form", "Engine ..."))
        self.trim_line.setPlaceholderText(_translate("Form", "Trim ..."))
        self.save_create_button.setText(_translate("Form", "Next"))
        self.vin_search_button.setText(_translate("Form", "VIN Search"))
        self.vin_line.setPlaceholderText(_translate("Form", "VIN ..."))
        self.abort_button.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
